-- index_templates: maps index template IDs to payor names and IDs
CREATE TABLE index_templates (
    index_template_id UUID PRIMARY KEY,
    payor_name        TEXT NOT NULL,
    payor_id          UUID NOT NULL
);

-- indexes: each ingested MRF index file, linked to an ingestor (payor)
CREATE TABLE indexes (
    id           UUID PRIMARY KEY,
    ingestor_id  UUID NOT NULL,
    deleted_at   TIMESTAMPTZ,
    archived_at  TIMESTAMPTZ
);

-- reporting_plans: insurance plans reported under Transparency in Coverage
CREATE TABLE reporting_plans (
    id               UUID PRIMARY KEY,
    index_id         UUID NOT NULL REFERENCES indexes(id),
    run_id           UUID NOT NULL,
    file_id          UUID NOT NULL,
    plan_id          TEXT NOT NULL,
    plan_name        TEXT,
    plan_id_type     TEXT,
    plan_market_type TEXT,
    created_at       TIMESTAMPTZ,
    issuer_name      TEXT,
    plan_sponsor_name TEXT
);

CREATE INDEX idx_reporting_plans_index_id        ON reporting_plans (index_id);
CREATE INDEX idx_reporting_plans_plan_id_type    ON reporting_plans (plan_id_type);
CREATE INDEX idx_reporting_plans_plan_market_type ON reporting_plans (plan_market_type);
CREATE INDEX idx_indexes_ingestor_id             ON indexes (ingestor_id);

-- form_5500: DOL Form 5500 filings from self-funded employers
-- All columns stored as TEXT to simplify CSV import; numeric fields can be cast at query time.
CREATE TABLE form_5500 (
    ack_id                        TEXT PRIMARY KEY,
    form_plan_year_begin_date     TEXT,
    form_tax_prd                  TEXT,
    type_plan_entity_cd           TEXT,
    type_dfe_plan_entity_cd       TEXT,
    initial_filing_ind            TEXT,
    amended_ind                   TEXT,
    final_filing_ind              TEXT,
    short_plan_yr_ind             TEXT,
    collective_bargain_ind        TEXT,
    f5558_application_filed_ind   TEXT,
    ext_automatic_ind             TEXT,
    dfvc_program_ind              TEXT,
    ext_special_ind               TEXT,
    ext_special_text              TEXT,
    plan_name                     TEXT,
    spons_dfe_pn                  TEXT,
    plan_eff_date                 TEXT,
    sponsor_dfe_name              TEXT,
    spons_dfe_dba_name            TEXT,
    spons_dfe_care_of_name        TEXT,
    spons_dfe_mail_us_address1    TEXT,
    spons_dfe_mail_us_address2    TEXT,
    spons_dfe_mail_us_city        TEXT,
    spons_dfe_mail_us_state       TEXT,
    spons_dfe_mail_us_zip         TEXT,
    spons_dfe_mail_foreign_addr1  TEXT,
    spons_dfe_mail_foreign_addr2  TEXT,
    spons_dfe_mail_foreign_city   TEXT,
    spons_dfe_mail_forgn_prov_st  TEXT,
    spons_dfe_mail_foreign_cntry  TEXT,
    spons_dfe_mail_forgn_postal_cd TEXT,
    spons_dfe_loc_us_address1     TEXT,
    spons_dfe_loc_us_address2     TEXT,
    spons_dfe_loc_us_city         TEXT,
    spons_dfe_loc_us_state        TEXT,
    spons_dfe_loc_us_zip          TEXT,
    spons_dfe_loc_foreign_address1 TEXT,
    spons_dfe_loc_foreign_address2 TEXT,
    spons_dfe_loc_foreign_city    TEXT,
    spons_dfe_loc_forgn_prov_st   TEXT,
    spons_dfe_loc_foreign_cntry   TEXT,
    spons_dfe_loc_forgn_postal_cd TEXT,
    spons_dfe_ein                 TEXT,
    spons_dfe_phone_num           TEXT,
    business_code                 TEXT,
    admin_name                    TEXT,
    admin_care_of_name            TEXT,
    admin_us_address1             TEXT,
    admin_us_address2             TEXT,
    admin_us_city                 TEXT,
    admin_us_state                TEXT,
    admin_us_zip                  TEXT,
    admin_foreign_address1        TEXT,
    admin_foreign_address2        TEXT,
    admin_foreign_city            TEXT,
    admin_foreign_prov_state      TEXT,
    admin_foreign_cntry           TEXT,
    admin_foreign_postal_cd       TEXT,
    admin_ein                     TEXT,
    admin_phone_num               TEXT,
    last_rpt_spons_name           TEXT,
    last_rpt_spons_ein            TEXT,
    last_rpt_plan_num             TEXT,
    admin_signed_date             TEXT,
    admin_signed_name             TEXT,
    spons_signed_date             TEXT,
    spons_signed_name             TEXT,
    dfe_signed_date               TEXT,
    dfe_signed_name               TEXT,
    tot_partcp_boy_cnt            TEXT,
    tot_active_partcp_cnt         TEXT,
    rtd_sep_partcp_rcvg_cnt       TEXT,
    rtd_sep_partcp_fut_cnt        TEXT,
    subtl_act_rtd_sep_cnt         TEXT,
    benef_rcvg_bnft_cnt           TEXT,
    tot_act_rtd_sep_benef_cnt     TEXT,
    partcp_account_bal_cnt        TEXT,
    sep_partcp_partl_vstd_cnt     TEXT,
    contrib_emplrs_cnt            TEXT,
    type_pension_bnft_code        TEXT,
    type_welfare_bnft_code        TEXT,
    funding_insurance_ind         TEXT,
    funding_sec412_ind            TEXT,
    funding_trust_ind             TEXT,
    funding_gen_asset_ind         TEXT,
    benefit_insurance_ind         TEXT,
    benefit_sec412_ind            TEXT,
    benefit_trust_ind             TEXT,
    benefit_gen_asset_ind         TEXT,
    sch_r_attached_ind            TEXT,
    sch_mb_attached_ind           TEXT,
    sch_sb_attached_ind           TEXT,
    sch_h_attached_ind            TEXT,
    sch_i_attached_ind            TEXT,
    sch_a_attached_ind            TEXT,
    num_sch_a_attached_cnt        TEXT,
    sch_c_attached_ind            TEXT,
    sch_d_attached_ind            TEXT,
    sch_g_attached_ind            TEXT,
    filing_status                 TEXT,
    date_received                 TEXT,
    valid_admin_signature         TEXT,
    valid_dfe_signature           TEXT,
    valid_sponsor_signature       TEXT,
    admin_phone_num_foreign       TEXT,
    spons_dfe_phone_num_foreign   TEXT,
    admin_name_same_spon_ind      TEXT,
    admin_address_same_spon_ind   TEXT,
    preparer_name                 TEXT,
    preparer_firm_name            TEXT,
    preparer_us_address1          TEXT,
    preparer_us_address2          TEXT,
    preparer_us_city              TEXT,
    preparer_us_state             TEXT,
    preparer_us_zip               TEXT,
    preparer_foreign_address1     TEXT,
    preparer_foreign_address2     TEXT,
    preparer_foreign_city         TEXT,
    preparer_foreign_prov_state   TEXT,
    preparer_foreign_cntry        TEXT,
    preparer_foreign_postal_cd    TEXT,
    preparer_phone_num            TEXT,
    preparer_phone_num_foreign    TEXT,
    tot_act_partcp_boy_cnt        TEXT,
    subj_m1_filing_req_ind        TEXT,
    compliance_m1_filing_req_ind  TEXT,
    m1_receipt_confirmation_code  TEXT,
    admin_manual_signed_date      TEXT,
    admin_manual_signed_name      TEXT,
    last_rpt_plan_name            TEXT,
    spons_manual_signed_date      TEXT,
    spons_manual_signed_name      TEXT,
    dfe_manual_signed_date        TEXT,
    dfe_manual_signed_name        TEXT,
    adopted_plan_perm_sec_act     TEXT,
    partcp_account_bal_cnt_boy    TEXT,
    sch_dcg_attached_ind          TEXT,
    num_sch_dcg_attached_cnt      TEXT,
    sch_mep_attached_ind          TEXT
);

CREATE INDEX idx_form_5500_spons_dfe_ein ON form_5500 (spons_dfe_ein);
CREATE INDEX idx_form_5500_sponsor_name  ON form_5500 (sponsor_dfe_name);
